project:
  type: website
  output-dir: _site

publish:
  gh-pages:
    repo-url: https://github.com/carsonslater/carsonslater.github.io
    branch: gh-pages

website:
  title: "Carson Slater"
  site-url: "https://carsonslater.github.io"
  favicon: images/logo.png
  open-graph:
    image: images/logo.png
    description: "Carson Slater's personal website - Statistics, Data Science, and Research"
  twitter-card:
    image: images/logo.png
    description: "Carson Slater's personal website - Statistics, Data Science, and Research"
  navbar:
    logo: images/logo.png
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: blog.qmd
        text: Blog
      - href: cv.qmd
        text: CV
    right:
      - icon: github
        href: https://github.com/carsonslater
      - icon: linkedin
        href: https://www.linkedin.com/in/carsonslateratbaylor/
      - icon: instagram
        href: https://www.instagram.com/slatercarson/
      - icon: envelope
        href: mailto:carson_slater1@baylor.edu
    background: dark

format:
  html:
    theme: superhero
    css: styles.css
    toc: true
